In [1]:
import sys
sys.path.append(r"../")
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy
import pingouin as pg
#from main import create_dataset
import dtale
import os
from plotly.offline import iplot, init_notebook_mode
import plotly.graph_objs as go
from statsmodels.stats.contingency_tables import mcnemar
os.getcwd()

'C:\\Users\\nogur\\Documents\\DeppClinic\\source\\projects\\Liat graphs'

In [2]:
suicidal_ideation_time2 = [

    'c_ssrs_t_last_1_clin',
    'c_ssrs_t_last_2_clin',
    'c_ssrs_t_last_3_clin',
    'c_ssrs_t_last_4_clin',
    'c_ssrs_t_last_5_clin',

 #   'c_ssrs_t_2weeks_1_clin',
    'c_ssrs_t_2weeks_2_clin',
    'c_ssrs_t_2weeks_3_clin',
    'c_ssrs_t_2weeks_4_clin',
    'c_ssrs_t_2weeks_5_clin',

    'c_ssrs_1',
    'c_ssrs_2',
    'c_ssrs_3',
    'c_ssrs_4',
    'c_ssrs_5',

 #   'chameleon_ideation_stu'
]

In [3]:
times = {'intake': ['intake_arm_1', 'pre_treatment_arm_1'],
         'time2' : ['5th_session_arm_1', 'control_5weeks_arm_1'],
         'time3' : ['followup_3month_arm_1', 'control_3month_arm_1', 'control_6month_arm_1'],
        }
# if not os.path.exists("Liat graphs/plots"):
#     os.mkdir("Liat graphs/plots")

group_names = {
    '0': 'invalid',
    '1': 'ipt', # חירום
    '2' : 'tau', # רגיל
    '3': 'control' # מינימלית
}

# for time in times.keys():
# #     print(time)
#     create_dataset(event_names = times[time], path = f"Liat graphs/data/{time}/DeppClinic_patient_data1.csv")

In [4]:
df_times = {
    'intake': pd.read_csv(r'data/old_processing_12_11/intake/DeppClinic_patient_data.csv'),
    'time2' : pd.read_csv(r'data/old_processing_12_11/time2/DeppClinic_patient_data.csv'),
    'time3' : pd.read_csv(r'data/old_processing_12_11/time3/DeppClinic_patient_data.csv')
         }

intake_target_variables =  ['suicidal_ideation', 'suicidal_behavior',
        'suicidal_attempt', 'ER', 'NSSI']

time2_target_variables = ['suicidal_ideation', 'suicidal_behavior', 
        'suicidal_attempt', 'ER', 'Psychiatric', 
        'NSSI', 'finished_treatment']

target_variables = {
    'intake': intake_target_variables,
    'time2': time2_target_variables, 
    'time3': time2_target_variables}

In [5]:
for time in times:
    df = df_times[time]
    df_times[time] = df[df['age_child_pre'] < 12.5]

In [6]:
def rename_groups(df, group_names):
    df['group'] = '0'
    df.loc[df['group___1'] == 1, 'group'] = '1'
    df.loc[df['group___2'] == 1, 'group'] = '2'
    df.loc[df['group___3'] == 1, 'group'] = '3'
    df['group'] = df['group'].map(group_names)
    return df

for time in times:
    df = df_times[time]
    df_times[time] = rename_groups(df, group_names)
    df_times[time] = df_times[time][df_times[time]["group"].isin(["ipt", "control"])]

## Intake

In [7]:
df_times['intake'].groupby('group').suicidal_ideation.value_counts()

group    suicidal_ideation
control  0                    29
         1                    26
ipt      1                    25
         0                    15
Name: count, dtype: int64

In [8]:
df_intake_ids = pd.read_csv(r"old_process_intake_ids.csv")
df_times['intake'] = df_times['intake'][df_times['intake'].id.isin(df_intake_ids.id)]

In [9]:
df_times['intake'].groupby('group').suicidal_ideation.value_counts()

group    suicidal_ideation
control  0                    20
         1                    15
ipt      1                    22
         0                    13
Name: count, dtype: int64

## Time 2

In [10]:
df_times['time2'].groupby('group').suicidal_ideation.value_counts()

group    suicidal_ideation
control  1                    29
         0                    10
ipt      1                    34
         0                     2
Name: count, dtype: int64

In [11]:
time2_ids = pd.read_csv(r"old_process_time2_ids.csv")
df_times['time2'] = df_times['time2'][df_times['time2'].id.isin(time2_ids.id)]
df_times['time2'].groupby('group').suicidal_ideation.value_counts()

group    suicidal_ideation
control  1                    18
         0                    10
ipt      1                    30
         0                     1
Name: count, dtype: int64

In [13]:
df_times['time2'][suicidal_ideation_time2 + ['suicidal_ideation', 'id', 'group']]

,c_ssrs_t_last_1_clin,c_ssrs_t_last_2_clin,c_ssrs_t_last_3_clin,c_ssrs_t_last_4_clin,c_ssrs_t_last_5_clin,c_ssrs_t_2weeks_2_clin,c_ssrs_t_2weeks_3_clin,c_ssrs_t_2weeks_4_clin,c_ssrs_t_2weeks_5_clin,c_ssrs_1,c_ssrs_2,c_ssrs_3,c_ssrs_4,c_ssrs_5,suicidal_ideation,id,group
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,0.0,0.0,1,S6442,control
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,1.0,0.0,0.0,1,E3613,control
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1,T5527,control
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,D4440,ipt
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,0.0,1,Y5064,ipt
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1,APPD9667,control
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1,R7617,control
40,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1,T4075,control
49,1.0,0.0,1.0,1.0,NaN,0.0,1.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,1,E5541,control
55,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1,N7245,ipt
58,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1,H0740,control
59,NaN,1.0,1.0,0.0,NaN,1.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,1,S5556,control
60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1,A9178,ipt
64,NaN,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Y7918,control
67,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1,D7663,control
78,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,E2391,ipt
102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,6978,ipt
103,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1,E2793,ipt
105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,H8412,ipt
114,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,J5218,ipt
115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,0.0,1.0,1.0,1,A8834,ipt
120,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1,O0003,ipt
125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,A6011,ipt
129,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,L9322,ipt
138,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1,4234,ipt
141,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,0.0,1,N6117,control
151,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,1,Y3607,ipt
155,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1,T7055,ipt
157,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,1.0,0.0,0.0,0.0,1,E1087,ipt
169,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1,O0973,ipt
185,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Y7548,ipt
198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1,A6507,ipt
202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1,E7385,ipt
215,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1,M2743,ipt
218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1,I1631,ipt
219,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1,M1508,ipt
222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1,Y6469,ipt
225,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1,Y4345,ipt
229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1,Y8189,ipt
238,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,1,H3340,ipt
242,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1,K2691,ipt
244,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1,A1651,control
250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,i6535,control
251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,N4125‏,ipt
252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,A3781,control
258,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,T8250,control
259,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,D5717ER,control
260,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,T7989,control
278,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1,H1354,control
350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0,M4805,control
353,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,A6439,control
354,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,N3892,control
358,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,LH003,control
360,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0,I4694,control
367,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1,M8113,control
371,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0,I6535,control
372,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0,N4125,control
374,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1,T8560,ipt
392,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1,N7753,control

In [ ]:
df_times['time2']

## Time 3

In [ ]:
df_times['time3'].groupby('group').suicidal_ideation.value_counts()

In [ ]:
time3_ids = pd.read_csv(r"old_process_time3_ids.csv")
df_times['time3'] = df_times['time2'][df_times['time3'].id.isin(time3_ids.id)]
df_times['time3'].groupby('group').suicidal_ideation.value_counts()

In [13]:
for target in target_variables['intake']:
    intake = df_times['intake']
    time2 = df_times['time2']
    
    intake = intake[['group', target]]
    time2 = time2[['group', target]]

    intake_values = intake.groupby('group')[target].sum()[['ipt', 'control']].values
    intake_gb = intake.groupby('group')[target].sum()[['ipt', 'control']]

    time2_values = time2.groupby('group')[target].sum()[['ipt', 'control']].values
    time2_gb = time2.groupby('group')[target].sum()[['ipt', 'control']]

    df = pd.DataFrame({'intake': intake_values, 'time2': time2_values})
    print(f"\n\n{target =}\n\n{intake_gb = }\n\n{time2_gb = }\n\n")
#     print('\n\n\n\n\n',target)
#     print(mcnemar(df.values, exact=False))

target ='suicidal_ideation'

intake_gb = group
ipt        23
control    17
Name: suicidal_ideation, dtype: int64

time2_gb = group
ipt        34
control    29
Name: suicidal_ideation, dtype: int64




target ='suicidal_behavior'

intake_gb = group
ipt        20
control    26
Name: suicidal_behavior, dtype: int64

time2_gb = group
ipt        34
control    32
Name: suicidal_behavior, dtype: int64




target ='suicidal_attempt'

intake_gb = group
ipt        20
control    26
Name: suicidal_attempt, dtype: int64

time2_gb = group
ipt        34
control    31
Name: suicidal_attempt, dtype: int64




target ='ER'

intake_gb = group
ipt        6
control    7
Name: ER, dtype: int64

time2_gb = group
ipt        32
control    26
Name: ER, dtype: int64




target ='NSSI'

intake_gb = group
ipt        20
control    26
Name: NSSI, dtype: int64

time2_gb = group
ipt        34
control    31
Name: NSSI, dtype: int64

In [9]:
for target in target_variables['intake']:
    intake = df_times['intake']
    time3 = df_times['time3']
    
    intake = intake[['group', target]]
    time3 = time3[['group', target]]

    intake_values = intake.groupby('group')[target].sum()[['ipt', 'control']].values
    time3_values = time3.groupby('group')[target].sum()[['ipt', 'control']].values

    df = pd.DataFrame({'intake': intake_values, 'time3': time3_values})
    print('\n\n\n\n\n', target)
    print(mcnemar(df.values, exact=False))

 suicidal_ideation
pvalue      1.0
statistic   0.0





 suicidal_behavior
pvalue      0.16913144470266755
statistic   1.890625





 suicidal_attempt
pvalue      0.16913144470266755
statistic   1.890625





 ER
pvalue      0.10017829422626791
statistic   2.7027027027027026





 NSSI
pvalue      0.16913144470266755
statistic   1.890625