In [1]:
import pandas as pd
import pandas_profiling as pp
import dtale
import seaborn as sns

In [2]:
df = pd.read_csv(r'../creating_the_clinic_dataset/preprocessed_data/merged_2021_and_2022.csv', na_values = ' ')
#df = df[df.redcap_event_name == 'intake_arm_1']

C:\Users\nogur\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning:

Columns (0,44,50,73,84,309,437,442,443,450,457,486,502,540,549,568,728,733,745,747,752,763,801,810,829,882,883,884,885,886,887,888,889,890,891,892,951,989,994,1000,1015,1045,1065,1066,1070,1071,1072,1073,1075,1076,1077,1080,1081,1098,1103,1119,1121,1172,1174,1193,1195,1196,1197,1203,1204,1205,1206,1358,1360,1361,1362,1368,1369,1370,1371,1486,1492,1493,1496,1497,1498,1499,1508,1516,1532,1535,1546) have mixed types.Specify dtype option on import or set low_memory=False.

In [31]:
c_ssrs = [
'c_ssrs_1_life',
'c_ssrs_2_life',
'c_ssrs_3_life',
'c_ssrs_4_life',
'c_ssrs_5_life',
'c_ssrs_6_life',
'c_ssrs_1_2weeks',
'c_ssrs_2_2weeks',
'c_ssrs_3_2weeks',
'c_ssrs_4_2weeks',
'c_ssrs_5_2weeks',
'c_ssrs_6_2weeks',
'c_ssrs_6_3month',
'c_ssrs_7_intake',
'c_ssrs_8_intake']

In [ ]:
c_ssrs_agg = {
'c_ssrs_1_life': 1,
'c_ssrs_2_life': 2,
'c_ssrs_3_life': 3,
'c_ssrs_4_life': 4,
'c_ssrs_5_life': 5,
'c_ssrs_6_life': 6,
    
'c_ssrs_1_2weeks':1,
'c_ssrs_2_2weeks':2,
'c_ssrs_3_2weeks':3,
'c_ssrs_4_2weeks':4,
'c_ssrs_5_2weeks':5,
'c_ssrs_6_2weeks':6,

'c_ssrs_6_3month':6
}

In [ ]:
c_ssrs_stb_life = max(
'c_ssrs_1_life': 1,
'c_ssrs_2_life': 2,
'c_ssrs_3_life': 3,
'c_ssrs_4_life': 4,
'c_ssrs_5_life': 5
'c_ssrs_6_life': 6)

c_ssrs_idea_life = max(
'c_ssrs_1_life': 1,
'c_ssrs_2_life': 2,
'c_ssrs_3_life': 3,
'c_ssrs_4_life': 4,
'c_ssrs_5_life': 5,
'c_ssrs_6_life': 6,)

c_ssrs_stb_2weeks = max(
'c_ssrs_1_2weeks':1,
'c_ssrs_2_2weeks':2,
'c_ssrs_3_2weeks':3,
'c_ssrs_4_2weeks':4,
'c_ssrs_5_2weeks':5,
'c_ssrs_6_2weeks':6,

c_ssrs_stb_recent = max(
'c_ssrs_1_2weeks':1,
'c_ssrs_2_2weeks':2,
'c_ssrs_3_2weeks':3,
'c_ssrs_4_2weeks':4,
'c_ssrs_5_2weeks':5,
'c_ssrs_6_2weeks':6,
'c_ssrs_6_3month':6
)

In [4]:
df[c_ssrs]

,c_ssrs_1_life,c_ssrs_2_life,c_ssrs_3_life,c_ssrs_4_life,c_ssrs_5_life,c_ssrs_6_life,c_ssrs_1_2weeks,c_ssrs_2_2weeks,c_ssrs_3_2weeks,c_ssrs_4_2weeks,c_ssrs_5_2weeks,c_ssrs_6_2weeks,c_ssrs_6_3month,c_ssrs_7_intake,c_ssrs_8_intake
114,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1954,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,-11.0,11.0
1955,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0
1956,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,15.0,30.0
1957,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,NaN,NaN,NaN,0.0,1.0,0.0,3.0
1958,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0

In [7]:
c_ssrs_rename = {
    'c_ssrs_1_life': 'כל החיים: האם קיווית למות או ללכת לישון מבלי להתעורר?',
'c_ssrs_2_life' : 'כל החיים: האם היו לך מחשבות להרוג את עצמך?',
'c_ssrs_3_life': ' האם חשבת איך לעשות את זה:כל החיים',
'c_ssrs_4_life': 'כל החיים: האם היו לך כוונות אכן לפעול לפי המחשבות של להרוג את עצמך?',
'c_ssrs_5_life': 'כל החיים: האם התחלת לתכנן או שכבר סגרת את פרטי התוכנית',
'c_ssrs_6_life': 'כל החיים: האם עשית משהו, התחלת לעשות משהו',
'c_ssrs_1_2weeks': 'שבועיים: האם קיווית למות או ללכת לישון מבלי להתעורר?', 
'c_ssrs_2_2weeks': 'שבועיים: האם היו לך מחשבות להרוג את עצמך?',
'c_ssrs_3_2weeks': 'שבועיים: האם חשבת איך לעשות את זה',
'c_ssrs_4_2weeks': 'שבועיים: האם היו לך כוונות אכן לפעול לפי המחשבות של להרוג את עצמך',
'c_ssrs_5_2weeks': 'שבועיים: האם התחלת לתכנן או שכבר סגרת את פרטי התוכנית',
'c_ssrs_6_2weeks': 'שבועיים: האם עשית משהו, התחלת לעשות משהו',
'c_ssrs_6_3month': '3 חודשים: האם עשית משהו, התחלת לעשות משהו',
'c_ssrs_7_intake': 'חודש: כמה פעמים עשית?',
'c_ssrs_8_intake': 'כל החיים: כמה פעמים עשית?'}

In [9]:
to_profile = df[c_ssrs + ['age_child_pre', 'gender', 'age_child']].rename(c_ssrs_rename, axis=1)
profile = pp.ProfileReport(to_profile, title="c_ssrs_intake")
profile.to_file("c_ssrs_intake.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]